name: pre-commit

on:
  pull_request:
  push:
    branches:
      - '**'

# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: terraform_fmt --all-files
